{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "train = pd.read_csv('train.csv') \n",
    "test = pd.read_csv('test.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def making_val_table(df):\n",
    "    '''입력받은 데이터셋의 유효성 검증을 위한 요약 테이블'''\n",
    "    # dtypes \n",
    "    df_dtypes = df.dtypes\n",
    "    \n",
    "    # nunique\n",
    "    df_nunique = df.nunique()\n",
    "    \n",
    "    # null_values\n",
    "    df_nan = df.isna().sum()\n",
    "    \n",
    "    val_table = pd.concat([df_dtypes, df_nunique, df_nan], axis=1)\n",
    "    val_table.columns = ['dtype', 'nunique', 'nan']\n",
    "        \n",
    "    return val_table.reset_index()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>dtype_train</th>\n",
       "      <th>nunique_train</th>\n",
       "      <th>nan_train</th>\n",
       "      <th>dtype_test</th>\n",
       "      <th>nunique_test</th>\n",
       "      <th>nan_test</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>index</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>ID</th>\n",
       "      <td>object</td>\n",
       "      <td>39609</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>10963.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>사고일시</th>\n",
       "      <td>object</td>\n",
       "      <td>18057</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>5548.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>요일</th>\n",
       "      <td>object</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>7.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>기상상태</th>\n",
       "      <td>object</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>5.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>시군구</th>\n",
       "      <td>object</td>\n",
       "      <td>199</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>192.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>도로형태</th>\n",
       "      <td>object</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>11.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>노면상태</th>\n",
       "      <td>object</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>6.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>사고유형</th>\n",
       "      <td>object</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>object</td>\n",
       "      <td>3.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>사고유형 - 세부분류</th>\n",
       "      <td>object</td>\n",
       "      <td>14</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>법규위반</th>\n",
       "      <td>object</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>가해운전자 차종</th>\n",
       "      <td>object</td>\n",
       "      <td>12</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>가해운전자 성별</th>\n",
       "      <td>object</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>가해운전자 연령</th>\n",
       "      <td>object</td>\n",
       "      <td>89</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>가해운전자 상해정도</th>\n",
       "      <td>object</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>피해운전자 차종</th>\n",
       "      <td>object</td>\n",
       "      <td>13</td>\n",
       "      <td>991</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>피해운전자 성별</th>\n",
       "      <td>object</td>\n",
       "      <td>3</td>\n",
       "      <td>991</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>피해운전자 연령</th>\n",
       "      <td>object</td>\n",
       "      <td>97</td>\n",
       "      <td>991</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>피해운전자 상해정도</th>\n",
       "      <td>object</td>\n",
       "      <td>6</td>\n",
       "      <td>991</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>사망자수</th>\n",
       "      <td>int64</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>중상자수</th>\n",
       "      <td>int64</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>경상자수</th>\n",
       "      <td>int64</td>\n",
       "      <td>18</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>부상자수</th>\n",
       "      <td>int64</td>\n",
       "      <td>9</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ECLO</th>\n",
       "      <td>int64</td>\n",
       "      <td>46</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            dtype_train  nunique_train  nan_train dtype_test  nunique_test  \\\n",
       "index                                                                        \n",
       "ID               object          39609          0     object       10963.0   \n",
       "사고일시             object          18057          0     object        5548.0   \n",
       "요일               object              7          0     object           7.0   \n",
       "기상상태             object              6          0     object           5.0   \n",
       "시군구              object            199          0     object         192.0   \n",
       "도로형태             object             11          0     object          11.0   \n",
       "노면상태             object              6          0     object           6.0   \n",
       "사고유형             object              3          0     object           3.0   \n",
       "사고유형 - 세부분류      object             14          0        NaN           NaN   \n",
       "법규위반             object             11          0        NaN           NaN   \n",
       "가해운전자 차종         object             12          0        NaN           NaN   \n",
       "가해운전자 성별         object              3          0        NaN           NaN   \n",
       "가해운전자 연령         object             89          0        NaN           NaN   \n",
       "가해운전자 상해정도       object              6          0        NaN           NaN   \n",
       "피해운전자 차종         object             13        991        NaN           NaN   \n",
       "피해운전자 성별         object              3        991        NaN           NaN   \n",
       "피해운전자 연령         object             97        991        NaN           NaN   \n",
       "피해운전자 상해정도       object              6        991        NaN           NaN   \n",
       "사망자수              int64              3          0        NaN           NaN   \n",
       "중상자수              int64              7          0        NaN           NaN   \n",
       "경상자수              int64             18          0        NaN           NaN   \n",
       "부상자수              int64              9          0        NaN           NaN   \n",
       "ECLO              int64             46          0        NaN           NaN   \n",
       "\n",
       "             nan_test  \n",
       "index                  \n",
       "ID                0.0  \n",
       "사고일시              0.0  \n",
       "요일                0.0  \n",
       "기상상태              0.0  \n",
       "시군구               0.0  \n",
       "도로형태              0.0  \n",
       "노면상태              0.0  \n",
       "사고유형              0.0  \n",
       "사고유형 - 세부분류       NaN  \n",
       "법규위반              NaN  \n",
       "가해운전자 차종          NaN  \n",
       "가해운전자 성별          NaN  \n",
       "가해운전자 연령          NaN  \n",
       "가해운전자 상해정도        NaN  \n",
       "피해운전자 차종          NaN  \n",
       "피해운전자 성별          NaN  \n",
       "피해운전자 연령          NaN  \n",
       "피해운전자 상해정도        NaN  \n",
       "사망자수              NaN  \n",
       "중상자수              NaN  \n",
       "경상자수              NaN  \n",
       "부상자수              NaN  \n",
       "ECLO              NaN  "
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 기상상태, 시군구 데이터의 unique 값이 각각 7vs6, 199vs 192로 다르다\n",
    "train_info = making_val_table(train)\n",
    "test_info = making_val_table(test)\n",
    "\n",
    "pd.merge(left=train_info, right=test_info, on='index', \n",
    "         how='left', suffixes=('_train','_test')).set_index('index')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# target 변수 지정\n",
    "y_train = train['ECLO']\n",
    "\n",
    "# train, test 데이터간 컬럼 동기화 \n",
    "cols = test.columns\n",
    "X_train = train[cols]\n",
    "X_test = test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def feat_eng(df):\n",
    "    # datetime 변환\n",
    "    df['사고일시'] = pd.to_datetime(df['사고일시'])\n",
    "    \n",
    "    # 월,일,시 컬럼 생성\n",
    "    df['월'] = df['사고일시'].dt.month\n",
    "    df['일'] = df['사고일시'].dt.day\n",
    "    df['시'] = df['사고일시'].dt.hour\n",
    "    \n",
    "    # 불필요 컬럼 제거\n",
    "    subs = ['ID','사고일시','기상상태','시군구']\n",
    "    df = df.drop(subs, axis=1)\n",
    "    \n",
    "    # one-hot encoding 실시\n",
    "    df = pd.get_dummies(df)\n",
    "    \n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_eng = feat_eng(X_train)\n",
    "X_test_eng = feat_eng(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X_train 데이터 shape : (39609, 30)\n",
      "y_train 데이터 shape : (39609,)\n",
      "\n",
      "X_test 데이터 shape : (10963, 30)\n"
     ]
    }
   ],
   "source": [
    "print(f'X_train 데이터 shape : {X_train_eng.shape}')\n",
    "print(f'y_train 데이터 shape : {y_train.shape}')\n",
    "print()\n",
    "print(f'X_test 데이터 shape : {X_test_eng.shape}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_val, y_train, y_val = train_test_split(X_train_eng, y_train , test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "No path specified. Models will be saved in: \"AutogluonModels/ag-20231117_021351/\"\n",
      "Presets specified: ['best_quality']\n",
      "Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=20\n",
      "Beginning AutoGluon training ... Time limit = 3600s\n",
      "AutoGluon will save models to \"AutogluonModels/ag-20231117_021351/\"\n",
      "AutoGluon Version:  0.8.2\n",
      "Python Version:     3.8.15\n",
      "Operating System:   Darwin\n",
      "Platform Machine:   x86_64\n",
      "Platform Version:   Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103\n",
      "Disk Space Avail:   28.26 GB / 245.11 GB (11.5%)\n",
      "Train Data Rows:    39609\n",
      "Train Data Columns: 30\n",
      "Label Column: ECLO\n",
      "Preprocessing data ...\n",
      "AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and label-values can't be converted to int).\n",
      "\tLabel info (max, min, mean, stddev): (74.0, 1.0, 4.73238, 2.8803)\n",
      "\tIf 'regression' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])\n",
      "Using Feature Generators to preprocess the data ...\n",
      "Fitting AutoMLPipelineFeatureGenerator...\n",
      "\tAvailable Memory:                    966.4 MB\n",
      "\tTrain Data (Original)  Memory Usage: 2.02 MB (0.2% of available memory)\n",
      "\tInferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.\n",
      "\tStage 1 Generators:\n",
      "\t\tFitting AsTypeFeatureGenerator...\n",
      "\t\t\tNote: Converting 27 features to boolean dtype as they only contain 2 unique values.\n",
      "\tStage 2 Generators:\n",
      "\t\tFitting FillNaFeatureGenerator...\n",
      "\tStage 3 Generators:\n",
      "\t\tFitting IdentityFeatureGenerator...\n",
      "\tStage 4 Generators:\n",
      "\t\tFitting DropUniqueFeatureGenerator...\n",
      "\tStage 5 Generators:\n",
      "\t\tFitting DropDuplicatesFeatureGenerator...\n",
      "\tUnused Original Features (Count: 1): ['노면상태_적설']\n",
      "\t\tThese features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.\n",
      "\t\tFeatures can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.\n",
      "\t\tThese features do not need to be present at inference time.\n",
      "\t\t('int', []) : 1 | ['노면상태_적설']\n",
      "\tTypes of features in original data (raw dtype, special dtypes):\n",
      "\t\t('int', []) : 29 | ['월', '일', '시', '요일_금요일', '요일_목요일', ...]\n",
      "\tTypes of features in processed data (raw dtype, special dtypes):\n",
      "\t\t('int', [])       :  3 | ['월', '일', '시']\n",
      "\t\t('int', ['bool']) : 26 | ['요일_금요일', '요일_목요일', '요일_수요일', '요일_월요일', '요일_일요일', ...]\n",
      "\t1.0s = Fit runtime\n",
      "\t29 features in original data used to generate 29 features in processed data.\n",
      "\tTrain Data (Processed) Memory Usage: 1.98 MB (0.2% of available memory)\n",
      "Data preprocessing and feature engineering runtime = 1.1s ...\n",
      "AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'\n",
      "\tThis metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.\n",
      "\tTo change this, specify the eval_metric parameter of Predictor()\n",
      "User-specified model hyperparameters to be fit:\n",
      "{\n",
      "\t'NN_TORCH': {},\n",
      "\t'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],\n",
      "\t'CAT': {},\n",
      "\t'XGB': {},\n",
      "\t'FASTAI': {},\n",
      "\t'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],\n",
      "\t'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],\n",
      "\t'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],\n",
      "}\n",
      "AutoGluon will fit 2 stack levels (L1 to L2) ...\n",
      "Fitting 11 L1 models ...\n",
      "Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 2398.67s of the 3598.89s of remaining time.\n",
      "\t-3.1698\t = Validation score   (-root_mean_squared_error)\n",
      "\t0.09s\t = Training   runtime\n",
      "\t0.16s\t = Validation runtime\n",
      "Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 2398.37s of the 3598.6s of remaining time.\n",
      "\t-3.2766\t = Validation score   (-root_mean_squared_error)\n",
      "\t0.06s\t = Training   runtime\n",
      "\t0.15s\t = Validation runtime\n",
      "Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2398.13s of the 3598.35s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBMXT_BAG_L1 to fail during training (ImportError)... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=14733, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/__init__.py\", line 8, in <module>\n",
      "    from .basic import Booster, Dataset, Sequence, register_logger\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 110, in <module>\n",
      "    _LIB = _load_lib()\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 101, in _load_lib\n",
      "    lib = ctypes.cdll.LoadLibrary(lib_path[0])\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 451, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 373, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "OSError: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_ray_fit()\u001b[39m (pid=14733, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 402, in _ray_fit\n",
      "    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 829, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/tabular/models/lgb/lgb_model.py\", line 74, in _fit\n",
      "    try_import_lightgbm()  # raise helpful error message if LightGBM isn't installed\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/common/utils/try_import.py\", line 133, in try_import_lightgbm\n",
      "    raise ImportError(\"`import lightgbm` failed. If you are using Mac OSX, \" \"Please try 'brew install libomp'. Detailed info: {}\".format(str(e)))\n",
      "ImportError: `import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "Fitting model: LightGBM_BAG_L1 ... Training model for up to 2390.25s of the 3590.48s of remaining time.\n",
      "2023-11-17 11:14:00,967\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:00,972\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:00,976\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:00,979\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:00,985\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:00,988\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:00,992\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBM_BAG_L1 to fail during training (ImportError)... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=14761, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/__init__.py\", line 8, in <module>\n",
      "    from .basic import Booster, Dataset, Sequence, register_logger\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 110, in <module>\n",
      "    _LIB = _load_lib()\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 101, in _load_lib\n",
      "    lib = ctypes.cdll.LoadLibrary(lib_path[0])\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 451, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 373, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "OSError: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_ray_fit()\u001b[39m (pid=14761, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 402, in _ray_fit\n",
      "    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 829, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/tabular/models/lgb/lgb_model.py\", line 74, in _fit\n",
      "    try_import_lightgbm()  # raise helpful error message if LightGBM isn't installed\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/common/utils/try_import.py\", line 133, in try_import_lightgbm\n",
      "    raise ImportError(\"`import lightgbm` failed. If you are using Mac OSX, \" \"Please try 'brew install libomp'. Detailed info: {}\".format(str(e)))\n",
      "ImportError: `import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 2382.27s of the 3582.49s of remaining time.\n",
      "2023-11-17 11:14:10,082\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:10,084\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:10,091\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:10,094\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:10,098\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:10,105\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:14:10,109\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 82 due to low memory. Expected memory usage reduced from 54.83% -> 15.0% of available memory...\n",
      "\t-3.2083\t = Validation score   (-root_mean_squared_error)\n",
      "\t9.34s\t = Training   runtime\n",
      "\t0.69s\t = Validation runtime\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 2371.98s of the 3572.21s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8465\t = Validation score   (-root_mean_squared_error)\n",
      "\t7.0s\t = Training   runtime\n",
      "\t0.28s\t = Validation runtime\n",
      "Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 2357.95s of the 3558.18s of remaining time.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 76 due to low memory. Expected memory usage reduced from 58.75% -> 15.0% of available memory...\n",
      "\t-3.1811\t = Validation score   (-root_mean_squared_error)\n",
      "\t3.54s\t = Training   runtime\n",
      "\t0.61s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 2353.64s of the 3553.86s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8518\t = Validation score   (-root_mean_squared_error)\n",
      "\t160.66s\t = Training   runtime\n",
      "\t1.32s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 2187.21s of the 3387.44s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8545\t = Validation score   (-root_mean_squared_error)\n",
      "\t9.65s\t = Training   runtime\n",
      "\t0.3s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 2170.09s of the 3370.32s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8576\t = Validation score   (-root_mean_squared_error)\n",
      "\t169.75s\t = Training   runtime\n",
      "\t0.6s\t = Validation runtime\n",
      "Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1992.81s of the 3193.04s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBMLarge_BAG_L1 to fail during training (ImportError)... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=15155, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/__init__.py\", line 8, in <module>\n",
      "    from .basic import Booster, Dataset, Sequence, register_logger\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 110, in <module>\n",
      "    _LIB = _load_lib()\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 101, in _load_lib\n",
      "    lib = ctypes.cdll.LoadLibrary(lib_path[0])\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 451, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 373, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "OSError: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_ray_fit()\u001b[39m (pid=15155, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 402, in _ray_fit\n",
      "    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 829, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/tabular/models/lgb/lgb_model.py\", line 74, in _fit\n",
      "    try_import_lightgbm()  # raise helpful error message if LightGBM isn't installed\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/common/utils/try_import.py\", line 133, in try_import_lightgbm\n",
      "    raise ImportError(\"`import lightgbm` failed. If you are using Mac OSX, \" \"Please try 'brew install libomp'. Detailed info: {}\".format(str(e)))\n",
      "ImportError: `import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "Repeating k-fold bagging: 2/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 1985.04s of the 3185.26s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "2023-11-17 11:20:51,546\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:20:51,548\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:20:51,550\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:20:51,554\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:20:51,557\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:20:51,559\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 11:20:51,561\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\t-2.8461\t = Validation score   (-root_mean_squared_error)\n",
      "\t14.19s\t = Training   runtime\n",
      "\t0.51s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1970.72s of the 3170.95s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8484\t = Validation score   (-root_mean_squared_error)\n",
      "\t326.03s\t = Training   runtime\n",
      "\t1.82s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 1798.17s of the 2998.39s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8528\t = Validation score   (-root_mean_squared_error)\n",
      "\t13.91s\t = Training   runtime\n",
      "\t0.41s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1790.85s of the 2991.08s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.855\t = Validation score   (-root_mean_squared_error)\n",
      "\t263.65s\t = Training   runtime\n",
      "\t0.83s\t = Validation runtime\n",
      "Repeating k-fold bagging: 3/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 1693.87s of the 2894.1s of remaining time.\n",
      "\tFitting 8 child models (S3F1 - S3F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8459\t = Validation score   (-root_mean_squared_error)\n",
      "\t18.11s\t = Training   runtime\n",
      "\t0.76s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1686.67s of the 2886.9s of remaining time.\n",
      "\tFitting 8 child models (S3F1 - S3F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8473\t = Validation score   (-root_mean_squared_error)\n",
      "\t409.36s\t = Training   runtime\n",
      "\t2.51s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 1599.49s of the 2799.72s of remaining time.\n",
      "\tFitting 8 child models (S3F1 - S3F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8543\t = Validation score   (-root_mean_squared_error)\n",
      "\t19.14s\t = Training   runtime\n",
      "\t0.51s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1590.23s of the 2790.46s of remaining time.\n",
      "\tFitting 8 child models (S3F1 - S3F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8543\t = Validation score   (-root_mean_squared_error)\n",
      "\t373.26s\t = Training   runtime\n",
      "\t1.31s\t = Validation runtime\n",
      "Repeating k-fold bagging: 4/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 1477.3s of the 2677.53s of remaining time.\n",
      "\tFitting 8 child models (S4F1 - S4F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8459\t = Validation score   (-root_mean_squared_error)\n",
      "\t22.52s\t = Training   runtime\n",
      "\t1.0s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1468.85s of the 2669.08s of remaining time.\n",
      "\tFitting 8 child models (S4F1 - S4F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8468\t = Validation score   (-root_mean_squared_error)\n",
      "\t495.74s\t = Training   runtime\n",
      "\t3.29s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 1378.13s of the 2578.36s of remaining time.\n",
      "\tFitting 8 child models (S4F1 - S4F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8534\t = Validation score   (-root_mean_squared_error)\n",
      "\t25.68s\t = Training   runtime\n",
      "\t0.65s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1368.19s of the 2568.42s of remaining time.\n",
      "\tFitting 8 child models (S4F1 - S4F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8538\t = Validation score   (-root_mean_squared_error)\n",
      "\t465.63s\t = Training   runtime\n",
      "\t1.66s\t = Validation runtime\n",
      "Repeating k-fold bagging: 5/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 1272.02s of the 2472.25s of remaining time.\n",
      "\tFitting 8 child models (S5F1 - S5F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8457\t = Validation score   (-root_mean_squared_error)\n",
      "\t27.44s\t = Training   runtime\n",
      "\t1.2s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1263.48s of the 2463.71s of remaining time.\n",
      "\tFitting 8 child models (S5F1 - S5F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8462\t = Validation score   (-root_mean_squared_error)\n",
      "\t586.45s\t = Training   runtime\n",
      "\t4.04s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 1168.87s of the 2369.09s of remaining time.\n",
      "\tFitting 8 child models (S5F1 - S5F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8529\t = Validation score   (-root_mean_squared_error)\n",
      "\t32.13s\t = Training   runtime\n",
      "\t0.79s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1158.53s of the 2358.76s of remaining time.\n",
      "\tFitting 8 child models (S5F1 - S5F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8541\t = Validation score   (-root_mean_squared_error)\n",
      "\t574.41s\t = Training   runtime\n",
      "\t2.0s\t = Validation runtime\n",
      "Repeating k-fold bagging: 6/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 1046.18s of the 2246.4s of remaining time.\n",
      "\tFitting 8 child models (S6F1 - S6F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8456\t = Validation score   (-root_mean_squared_error)\n",
      "\t31.64s\t = Training   runtime\n",
      "\t1.35s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1037.88s of the 2238.1s of remaining time.\n",
      "\tFitting 8 child models (S6F1 - S6F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8461\t = Validation score   (-root_mean_squared_error)\n",
      "\t678.37s\t = Training   runtime\n",
      "\t4.97s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 941.89s of the 2142.12s of remaining time.\n",
      "\tFitting 8 child models (S6F1 - S6F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8525\t = Validation score   (-root_mean_squared_error)\n",
      "\t38.1s\t = Training   runtime\n",
      "\t1.05s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 932.04s of the 2132.27s of remaining time.\n",
      "\tFitting 8 child models (S6F1 - S6F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8539\t = Validation score   (-root_mean_squared_error)\n",
      "\t685.72s\t = Training   runtime\n",
      "\t2.36s\t = Validation runtime\n",
      "Repeating k-fold bagging: 7/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 817.0s of the 2017.23s of remaining time.\n",
      "\tFitting 8 child models (S7F1 - S7F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8455\t = Validation score   (-root_mean_squared_error)\n",
      "\t36.74s\t = Training   runtime\n",
      "\t1.56s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 807.88s of the 2008.1s of remaining time.\n",
      "\tFitting 8 child models (S7F1 - S7F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8458\t = Validation score   (-root_mean_squared_error)\n",
      "\t776.84s\t = Training   runtime\n",
      "\t5.95s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L1 ... Training model for up to 704.9s of the 1905.13s of remaining time.\n",
      "\tFitting 8 child models (S7F1 - S7F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8528\t = Validation score   (-root_mean_squared_error)\n",
      "\t45.0s\t = Training   runtime\n",
      "\t1.19s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 693.86s of the 1894.09s of remaining time.\n",
      "\tFitting 8 child models (S7F1 - S7F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8541\t = Validation score   (-root_mean_squared_error)\n",
      "\t953.09s\t = Training   runtime\n",
      "\t2.71s\t = Validation runtime\n",
      "Repeating k-fold bagging: 8/20\n",
      "Fitting model: CatBoost_BAG_L1 ... Training model for up to 422.6s of the 1622.83s of remaining time.\n",
      "\tFitting 8 child models (S8F1 - S8F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8455\t = Validation score   (-root_mean_squared_error)\n",
      "\t39.74s\t = Training   runtime\n",
      "\t1.73s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 416.5s of the 1616.73s of remaining time.\n",
      "\tFitting 8 child models (S8F1 - S8F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8457\t = Validation score   (-root_mean_squared_error)\n",
      "\t1589.45s\t = Training   runtime\n",
      "\t6.85s\t = Validation runtime\n",
      "Completed 8/20 k-fold bagging repeats ...\n",
      "Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 800.84s of remaining time.\n",
      "\t-2.8446\t = Validation score   (-root_mean_squared_error)\n",
      "\t0.3s\t = Training   runtime\n",
      "\t0.0s\t = Validation runtime\n",
      "Fitting 9 L2 models ...\n",
      "Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 800.52s of the 800.51s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBMXT_BAG_L2 to fail during training (ImportError)... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=17283, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/__init__.py\", line 8, in <module>\n",
      "    from .basic import Booster, Dataset, Sequence, register_logger\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 110, in <module>\n",
      "    _LIB = _load_lib()\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 101, in _load_lib\n",
      "    lib = ctypes.cdll.LoadLibrary(lib_path[0])\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 451, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 373, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "OSError: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_ray_fit()\u001b[39m (pid=17283, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 402, in _ray_fit\n",
      "    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 829, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/tabular/models/lgb/lgb_model.py\", line 74, in _fit\n",
      "    try_import_lightgbm()  # raise helpful error message if LightGBM isn't installed\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/common/utils/try_import.py\", line 133, in try_import_lightgbm\n",
      "    raise ImportError(\"`import lightgbm` failed. If you are using Mac OSX, \" \"Please try 'brew install libomp'. Detailed info: {}\".format(str(e)))\n",
      "ImportError: `import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "Fitting model: LightGBM_BAG_L2 ... Training model for up to 797.11s of the 797.1s of remaining time.\n",
      "2023-11-17 12:00:34,333\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:34,334\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:34,339\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:34,341\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:34,342\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:34,343\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:34,346\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBM_BAG_L2 to fail during training (ImportError)... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=17300, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/__init__.py\", line 8, in <module>\n",
      "    from .basic import Booster, Dataset, Sequence, register_logger\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 110, in <module>\n",
      "    _LIB = _load_lib()\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 101, in _load_lib\n",
      "    lib = ctypes.cdll.LoadLibrary(lib_path[0])\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 451, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 373, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "OSError: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_ray_fit()\u001b[39m (pid=17300, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 402, in _ray_fit\n",
      "    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 829, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/tabular/models/lgb/lgb_model.py\", line 74, in _fit\n",
      "    try_import_lightgbm()  # raise helpful error message if LightGBM isn't installed\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/common/utils/try_import.py\", line 133, in try_import_lightgbm\n",
      "    raise ImportError(\"`import lightgbm` failed. If you are using Mac OSX, \" \"Please try 'brew install libomp'. Detailed info: {}\".format(str(e)))\n",
      "ImportError: `import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 794.15s of the 794.13s of remaining time.\n",
      "2023-11-17 12:00:37,372\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:37,373\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:37,375\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:37,375\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:37,377\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:37,378\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:00:37,379\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 96 due to low memory. Expected memory usage reduced from 46.51% -> 15.0% of available memory...\n",
      "\t-2.906\t = Validation score   (-root_mean_squared_error)\n",
      "\t8.3s\t = Training   runtime\n",
      "\t0.47s\t = Validation runtime\n",
      "Fitting model: CatBoost_BAG_L2 ... Training model for up to 785.14s of the 785.13s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8441\t = Validation score   (-root_mean_squared_error)\n",
      "\t4.07s\t = Training   runtime\n",
      "\t0.24s\t = Validation runtime\n",
      "Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 778.21s of the 778.2s of remaining time.\n",
      "\tWarning: Reducing model 'n_estimators' from 300 -> 84 due to low memory. Expected memory usage reduced from 53.4% -> 15.0% of available memory...\n",
      "\t-2.877\t = Validation score   (-root_mean_squared_error)\n",
      "\t2.01s\t = Training   runtime\n",
      "\t0.38s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 775.64s of the 775.63s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.849\t = Validation score   (-root_mean_squared_error)\n",
      "\t196.45s\t = Training   runtime\n",
      "\t0.64s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L2 ... Training model for up to 576.47s of the 576.45s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8493\t = Validation score   (-root_mean_squared_error)\n",
      "\t5.35s\t = Training   runtime\n",
      "\t0.2s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 567.77s of the 567.76s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8569\t = Validation score   (-root_mean_squared_error)\n",
      "\t82.32s\t = Training   runtime\n",
      "\t0.36s\t = Validation runtime\n",
      "Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 481.88s of the 481.87s of remaining time.\n",
      "\tFitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\tWarning: Exception caused LightGBMLarge_BAG_L2 to fail during training (ImportError)... Skipping this model.\n",
      "\t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=17630, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/__init__.py\", line 8, in <module>\n",
      "    from .basic import Booster, Dataset, Sequence, register_logger\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 110, in <module>\n",
      "    _LIB = _load_lib()\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/basic.py\", line 101, in _load_lib\n",
      "    lib = ctypes.cdll.LoadLibrary(lib_path[0])\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 451, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/ctypes/__init__.py\", line 373, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "OSError: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "\u001b[36mray::_ray_fit()\u001b[39m (pid=17630, ip=127.0.0.1)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py\", line 402, in _ray_fit\n",
      "    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/core/models/abstract/abstract_model.py\", line 829, in fit\n",
      "    out = self._fit(**kwargs)\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/tabular/models/lgb/lgb_model.py\", line 74, in _fit\n",
      "    try_import_lightgbm()  # raise helpful error message if LightGBM isn't installed\n",
      "  File \"/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/autogluon/common/utils/try_import.py\", line 133, in try_import_lightgbm\n",
      "    raise ImportError(\"`import lightgbm` failed. If you are using Mac OSX, \" \"Please try 'brew install libomp'. Detailed info: {}\".format(str(e)))\n",
      "ImportError: `import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n",
      "  Referenced from: <D21A7969-4567-3BC7-94ED-6A9E83AE9D78> /Users/itaeyun/opt/anaconda3/envs/dev/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so\n",
      "  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)\n",
      "Repeating k-fold bagging: 2/20\n",
      "Fitting model: CatBoost_BAG_L2 ... Training model for up to 478.02s of the 478.01s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "2023-11-17 12:05:59,274\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:05:59,323\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:05:59,384\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:05:59,386\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:05:59,391\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:05:59,395\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2023-11-17 12:05:59,402\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\t-2.8435\t = Validation score   (-root_mean_squared_error)\n",
      "\t15.22s\t = Training   runtime\n",
      "\t0.44s\t = Validation runtime\n",
      "Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 463.39s of the 463.38s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8465\t = Validation score   (-root_mean_squared_error)\n",
      "\t278.71s\t = Training   runtime\n",
      "\t1.36s\t = Validation runtime\n",
      "Fitting model: XGBoost_BAG_L2 ... Training model for up to 377.58s of the 377.56s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8455\t = Validation score   (-root_mean_squared_error)\n",
      "\t12.35s\t = Training   runtime\n",
      "\t0.4s\t = Validation runtime\n",
      "Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 367.08s of the 367.07s of remaining time.\n",
      "\tFitting 8 child models (S2F1 - S2F8) | Fitting with ParallelLocalFoldFittingStrategy\n",
      "\t-2.8542\t = Validation score   (-root_mean_squared_error)\n",
      "\t180.22s\t = Training   runtime\n",
      "\t0.74s\t = Validation runtime\n",
      "Completed 2/20 k-fold bagging repeats ...\n",
      "Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the 265.37s of remaining time.\n",
      "\t-2.8284\t = Validation score   (-root_mean_squared_error)\n",
      "\t0.34s\t = Training   runtime\n",
      "\t0.0s\t = Validation runtime\n",
      "AutoGluon training complete, total runtime = 3335.0s ... Best model: \"WeightedEnsemble_L3\"\n",
      "TabularPredictor saved. To load, use: predictor = TabularPredictor.load(\"AutogluonModels/ag-20231117_021351/\")\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from autogluon.tabular import TabularDataset, TabularPredictor\n",
    "\n",
    "# 'ECLO' 열에 대해 결측치를 평균 값으로 대체하고, 무한대 값을 최대값으로 대체\n",
    "y_train = y_train.replace([np.inf, -np.inf], np.nan)\n",
    "y_train = y_train.fillna(y_train.mean())\n",
    "\n",
    "# 타겟 변수를 데이터 프레임에 추가\n",
    "X_train_eng['ECLO'] = y_train\n",
    "\n",
    "# 기타 열에 대해 결측치를 평균 값으로 대체하고, 무한대 값을 해당 열의 최대값으로 대체\n",
    "X_train_eng = X_train_eng.replace([np.inf, -np.inf], np.nan)\n",
    "X_train_eng = X_train_eng.apply(lambda x: x.fillna(x.mean()), axis=0)\n",
    "\n",
    "# AutoGluon 학습을 위한 데이터 형태로 변환\n",
    "train_data = TabularDataset(data=X_train_eng)\n",
    "\n",
    "predictor = TabularPredictor(label='ECLO').fit(\n",
    "    train_data=train_data, \n",
    "    presets='best_quality', \n",
    "    time_limit=60*60\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 예측하기\n",
    "pred_y = predictor.predict(X_test_eng)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ID</th>\n",
       "      <th>ECLO</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>ACCIDENT_39609</td>\n",
       "      <td>4.348880</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>ACCIDENT_39610</td>\n",
       "      <td>4.108166</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ACCIDENT_39611</td>\n",
       "      <td>5.254338</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>ACCIDENT_39612</td>\n",
       "      <td>5.115234</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>ACCIDENT_39613</td>\n",
       "      <td>5.009536</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10958</th>\n",
       "      <td>ACCIDENT_50567</td>\n",
       "      <td>6.624053</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10959</th>\n",
       "      <td>ACCIDENT_50568</td>\n",
       "      <td>5.320106</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10960</th>\n",
       "      <td>ACCIDENT_50569</td>\n",
       "      <td>4.731536</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10961</th>\n",
       "      <td>ACCIDENT_50570</td>\n",
       "      <td>4.807998</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10962</th>\n",
       "      <td>ACCIDENT_50571</td>\n",
       "      <td>5.138278</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>10963 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                   ID      ECLO\n",
       "0      ACCIDENT_39609  4.348880\n",
       "1      ACCIDENT_39610  4.108166\n",
       "2      ACCIDENT_39611  5.254338\n",
       "3      ACCIDENT_39612  5.115234\n",
       "4      ACCIDENT_39613  5.009536\n",
       "...               ...       ...\n",
       "10958  ACCIDENT_50567  6.624053\n",
       "10959  ACCIDENT_50568  5.320106\n",
       "10960  ACCIDENT_50569  4.731536\n",
       "10961  ACCIDENT_50570  4.807998\n",
       "10962  ACCIDENT_50571  5.138278\n",
       "\n",
       "[10963 rows x 2 columns]"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sample_submission = pd.read_csv(\"sample_submission.csv\")\n",
    "\n",
    "baseline_submission = sample_submission.copy()\n",
    "baseline_submission['ECLO'] = pred_y\n",
    "baseline_submission "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "baseline_submission.to_csv('fourth_submit.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "# csv 파일을 읽어옵니다.\n",
    "df = pd.read_csv('third_submit.csv')\n",
    "\n",
    "# 빈 값을 0으로 채웁니다.\n",
    "df = df.fillna(0)\n",
    "\n",
    "# 변경된 데이터를 다시 csv 파일로 저장합니다.\n",
    "df.to_csv('fourth_submit.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.15 64-bit ('dev')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.15"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "329e22198b68d8e60cd009d73b7185815e21aa24b6d9ff67db9978dd5b8ddb29"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
